### ISSUE TITLE
Add support for PAT02-1B

### ISSUE THREAD

**Issue by djanssen1** [Inversion-NL/com.philio#21]
Hi there,

Can you add support for PAT02-1B sensor. It is a sensor for temperature and humidity and look like the multisensor series

https://www.robbshop.nl/2-in-1-temperatuur-en-luchtvochtigheids-sensor-z-wave-plus-philiotech?sqr=philio%20temperat&

**Comment by MbenzNo** [comment]
I would also like to have support for the PAT02-B sensor. If I try to include it as a generic Z-Wave device it is identified as a slave, exchanges security keys , command classes and so on, but in the end it stops at retrive wake up interval, and ends with the message : No Z-Wave device has been found. There does not appear an unknown device icon, but if I try to include it again it fails due to the device is included. I have to remove it from settings.

**Comment by cscottmcqueen** [comment]
Also would like support added for this device.

**Comment by TedTolboom** [comment]
See Pull Request #24

**Comment by cscottmcqueen** [comment]
Just to confirm PAT02-1B tested and working great in v0.0.20

Many thanks

**Comment by djanssen1** [comment]
I already tested and worked with Ted, Ted thanks! I'm closing this one..

**Comment by grolsch1986** [comment]
the temper alarm is always on whats the problem off this????
